### ISSUE TITLE
Could you release the trained model for the scene text recognition?

### ISSUE THREAD

**Issue by dpengwen** [Wang-Tianwei/Decoupled-attention-network#1]
Hi,
  Thanks for your released code. Could you release the trained model for the scene text recognition?  We would like to compare our method with your method comprehensively. 

Thank  you~

**Comment by Wang-Tianwei** [comment]
Yes, we will release the trained model for scene text recognition in the next few days.

**Comment by dpengwen** [comment]
Thanks~

**Comment by Wang-Tianwei** [comment]
The trained models have been uploaded. The model for scene text recognition is single-directional and nearly well trained, thus its performance may be lower than we report in the paper (which is a bi-directional model).
