### ISSUE TITLE
关于index out of range的问题

### ISSUE THREAD

**Issue by WDONG66** [Wang-Tianwei/Decoupled-attention-network#13]
您好，我把“Test”改成“Train”之后
在DAN.py,line 206 这一行
prev_emb = self.char_embeddings.index_select(0,text[:,i])
RuntimeError: index out of range at /pytorch/aten/src/TH/generic/THTensorMath.cpp
但是我发现是nsteps和text的纵行匹配的
（但是另外每次nsteps这个值都会变）
请问您知道什么原因吗？

谢谢~

**Comment by Wang-Tianwei** [comment]
你好，感谢关注！

这个应该是最大类别数超过了预设的值。

nsteps这个值训练时是按照batch中最长序列的长度来的，所以每个batch都不一样。
