### ISSUE TITLE
关于attention maps使用sigmoid的问题

### ISSUE THREAD

**Issue by Pay20Y** [Wang-Tianwei/Decoupled-attention-network#14]
作者您好，您在生成attention maps时使用了sigmoid +normalization，而没有使用传统的softmax。请问是为什么呢？是做过相关的实验吗？谢谢！

**Comment by Wang-Tianwei** [comment]
都可以，效果差不多。这里使用sigmoid是为了得到更平滑的attention map。

**Comment by Pay20Y** [comment]
好的，谢谢！
