### ISSUE TITLE
What's meaning of bi-directional model ?

### ISSUE THREAD

**Issue by YuNie24** [Wang-Tianwei/Decoupled-attention-network#17]
In https://github.com/Wang-Tianwei/Decoupled-attention-network/issues/1#issuecomment-569848838 issue, 
you mentioned that the performance of paper could be get from bi-directional model.

I have checked the accuracy of various test dataset and accuracies were lower than paper.
So I want to try the best condition of models.

Is "bi-directional model" related with DTD module?
But "pre_lstm" in DTD is already using "bidirectional=True" flag.
I'm confusing if we can apply "bidirectional=True" with nn.GRU instead of nn.GRUCell(your code).

It looks nn.GRUCell is proper method because DTD of DAN have to check character of each step.

**Comment by Wang-Tianwei** [comment]
"Bi-directional model" means double CAM-DTD modules, one for forward prediction (reading order) and the other for reverse prediction. And the final result is determined by which direction yields higher probability.

**Comment by YuNie24** [comment]
okay, it make sense.
In paper, you mentioned that "We use the bi-directional decoder proposed in (Shi et al. 2018) for final prediction"
Thank you :)
