### ISSUE TITLE
为啥注意力权重和特征图计算后又过了一个pre_lstm

### ISSUE THREAD

**Issue by medyuanxiao** [Wang-Tianwei/Decoupled-attention-network#2]
如题，论文里没有提到这个lstm，加了这一层速度会慢不少吧

**Comment by medyuanxiao** [comment]
# weighted sum
        C = feature.view(nB, 1, nC, nH, nW) * A.view(nB, nT, 1, nH, nW)
        C = C.view(nB,nT,nC,-1).sum(3).transpose(1,0)
        C, _ = self.pre_lstm(C)

**Comment by Wang-Tianwei** [comment]
非常抱歉，这是论文中的疏忽，这一层实验中是存在的，论文中写漏了。我们也补做过对比实验，速度上加这层确实会拖慢一些，它对收敛和最终结果影响都很小。去掉也是可行的。
