### ISSUE TITLE
关于中文识别的有关问题？

### ISSUE THREAD

**Issue by whuhangzhang** [Wang-Tianwei/Decoupled-attention-network#20]
@Wang-Tianwei 您好，我查看了您的issue列表，想问 MORAN_v2和Decoupled-attention-network两个repo哪一个比较适合ICDAR2019 ReCTS这样的数据集呢？在您之前的回答中https://github.com/Wang-Tianwei/Decoupled-attention-network/issues/3 ，哪一个方法效果会比较适合这一数据集呢

**Comment by Wang-Tianwei** [comment]
你好，以我们比赛时的经验，中文上DAN-2D好一点

**Comment by whuhangzhang** [comment]
DAN-2D是指Decoupled-attention-network这个文章么，十分感谢~
