### ISSUE TITLE
包括中文字符的数据集表现如何？

### ISSUE THREAD

**Issue by xiliu** [Wang-Tianwei/Decoupled-attention-network#3]
你好，请问该方法在其他包括中字符的数据集表现如何？如icpr2018、ReCTs、LSVT、art、ctw1500数据集。谢谢

**Comment by Wang-Tianwei** [comment]
你好，这几个数据集我只试过ReCTS。在ReCTS上这个方法表现还不错，帮助我们取得了今年比赛识别任务的冠军。 大概情况是会比CTC和普通的attention (ASTER、MORAN去掉矫正器部分) 高一点。

**Comment by xiliu** [comment]
感谢你的回复
