### ISSUE TITLE
icdar 2015 dataset support

### ISSUE THREAD

**Issue by ghost** [Wang-Tianwei/Decoupled-attention-network#7]
@Wang-Tianwei
Thank you for your hard work

Will there be support to input icdar2015 dataset for training

**Comment by Wang-Tianwei** [comment]
Thank you for your interest in our work.

I have no plans to adapt to a certain form of dataset.
For the support of icdar2015 dataset, you can refer to this repo: https://github.com/jiangxiluning/FOTS.PyTorch/tree/master/FOTS/data_loader/dataset.py
