### ISSUE TITLE
请教，测试和训练准确率一直为0.

### ISSUE THREAD

**Issue by ZipengFeng** [Wang-Tianwei/Decoupled-attention-network#8]
用您提供的场景文字识别模型，测试准确率一直为零；自己训练准确率也是0. 配置文件中的路径都改过了，环境也与您提供的一致。不知道还有什么问题。烦请解答一下可以吗？

**Comment by Wang-Tianwei** [comment]
你好。训练时loss变化是否正常？

**Comment by ZipengFeng** [comment]
> 你好。训练时loss变化是否正常？

loss也不下降。

**Comment by Wang-Tianwei** [comment]
直接用提供的模型具体输出是什么样呢？我怀疑可能是给的label和代码需要的不对应

**Comment by ZipengFeng** [comment]
用提供的模型，我输出了同一个batch的label和预测结果：
预测结果像是随机的。
target tensor([[ 2, 37,  2, 12,  1,  3, 11, 37,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 16,  5, 16, 16,  5, 18, 37,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 16, 15, 19, 20, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 15,  6,  6,  9,  3,  5, 37,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 20,  9, 18,  5,  4, 14,  5, 19, 19, 37,  0,  0,  0],
        [ 2, 37, 11,  9, 12, 12, 19, 37,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 19,  8, 15, 18, 20, 37,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37,  2, 18,  5,  1, 11, 37,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37,  3, 15, 21, 12,  4, 37,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 19,  1, 22,  5, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 25, 15, 21, 18, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 12,  9,  6,  5, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 10, 21,  2,  9, 12,  5,  5, 37,  0,  0,  0,  0,  0],
        [ 2, 37, 12,  9, 14,  5, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 20, 18,  1, 22,  5, 12,  3,  1, 18,  4, 19, 37,  0],
        [ 2, 37,  6, 18, 15, 13, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 13,  1,  3,  8,  9, 14,  5, 37,  0,  0,  0,  0,  0],
        [ 2, 37,  4,  1, 25, 37,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37,  3, 12, 15, 19,  9, 14,  7, 37,  0,  0,  0,  0,  0],
        [ 2, 37,  4, 15, 23, 14, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 19,  1, 12,  5, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 16,  5,  1,  3, 15,  3, 11, 19, 37,  0,  0,  0,  0],
        [ 2, 37, 19, 16,  9, 18,  9, 20, 37,  0,  0,  0,  0,  0,  0],
        [ 2, 37,  4, 15, 21,  2, 12,  5, 19, 37,  0,  0,  0,  0,  0],
        [ 2, 37,  7,  9, 14, 37,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 23,  8,  9, 19, 11, 25, 37,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 22, 15,  4, 11,  1, 37,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 19, 16,  5,  3,  9,  1, 12, 37,  0,  0,  0,  0,  0],
        [ 2, 37,  8, 15, 21, 19,  5, 37,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 23,  8,  9, 19, 11, 25, 37,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 10,  1,  3, 11, 19, 37,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37,  6,  1, 13, 15, 21, 19, 37,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 19, 21, 16, 16, 12,  9,  5, 19, 37,  0,  0,  0,  0],
        [ 2, 37, 27, 35, 30, 32, 37,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 2, 37,  3, 21, 12, 22,  5, 18, 37,  0,  0,  0,  0,  0,  0],
        [ 2, 37, 19, 20, 18,  5,  5, 20, 37,  0,  0,  0,  0,  0,  0]])


output tensor([[ -94.4965,  -95.7829,  -77.6298,  ...,  -96.9108,  -96.0080,
          -91.8993],
        [-152.6245, -152.4182, -150.0034,  ..., -154.1898, -153.3203,
         -151.4125],
        [-101.3825,  -83.6655, -101.8822,  ..., -101.5693, -103.0678,
          -97.9568],
        ...,
        [-157.9634, -151.0819, -153.6248,  ..., -154.8469, -155.2623,
         -155.6859],
        [ -38.3115,  -40.0457,  -39.2524,  ...,  -42.3008,  -38.6655,
          -36.5758],
        [ 157.4700,  140.8690,  137.2421,  ...,  134.7615,  137.2202,
          150.5161]], device='cuda:0', grad_fn=<CopySlices>)

**Comment by Wang-Tianwei** [comment]
模型输出解码成字符串，就是 utils.py line 69 的prdt_texts是否合理。

**Comment by ZipengFeng** [comment]
啊哈，结果是对的，那应该是计算指标的代码有点问题。我再看看，非常感谢您的耐心回答！
labels: ["b'brow'", "b'glass'", "b'only'", "b'beware'", "b'alligator'", "b'teeth'", "b'gas'", "b'180'", "b'moto'", "b'jeanswear'", "b'iiyama'", "b'pocket'", "b'flash'", "b'reader'", "b'technology'", "b'for'", "b'jungle'", "b'snout'", "b'graphic'", "b'mastering'", "b'the'", "b'jfc'", "b'3rd'", "b'edition'", "b'java'", "b'doublemint'", "b'chewing'", "b'gum'", "b'september'", "b'germ'", "b'ftrtft'", "b'2002'", "b'maximum'", "b'load'", "b'1600'", "b'persons'"]
prdt_texts: ['brow', 'glass', 'only', 'beware', 'alligator', 'teeth', 'gas', '180', 'moto', 'inanswear', 'iivama', 'pocket', 'flash', 'reader', 'technology', 'for', 'jungle', 'sivout', 'graphic', 'mastering', 'the', 'jfc', '3rd', 'edition', 'java', 'doublemint', 'chewing', 'gum', 'september', 'germ', 'ftrtft', '2002', 'maximum', 'load', '1600', 'persons']

**Comment by Wang-Tianwei** [comment]
嗯嗯，不用谢。看这样子像是字符转码有点问题

**Comment by ZipengFeng** [comment]
啊哈，找到原因了。原来我用的python3。是python2和python3编码格式的区别导致的label不同。

**Comment by neverstoplearn** [comment]
> 啊哈，找到原因了。原来我用的python3。是python2和python3编码格式的区别导致的label不同。

你好，请问应该如何修改代码避免这个错误。
