### ISSUE TITLE
关于DTD的小白问题

### ISSUE THREAD

**Issue by DongfeiJi** [Wang-Tianwei/Decoupled-attention-network#9]
您好，请问DTD中的
self.char_embeddings = Parameter(torch.randn(nclass, nchannel))
后面进行decode用到了多次
具体起什么作用呀，可以大概帮忙介绍下么，非常感谢

**Comment by Wang-Tianwei** [comment]
这里就是一个embedding层，也可以用torch.nn.Embedding来实现。作用一般来讲是引入上一次解码的结果来加强隐形语言模型学习，在一些attention（例如transformer）中，也起到指示当前解码状态的作用。这个在attention机制的应用中比较普遍（可以追溯到最早的attention文章[1]的Sec 3.3.1中）。

[1] Bahdanau et al. Neural Machine Translation by Jointly Learning to Align and Translate. ICLR 2015.

**Comment by DongfeiJi** [comment]
非常感谢，新年快乐❤️

**Comment by DongfeiJi** [comment]
> 这里就是一个embedding层，也可以用torch.nn.Embedding来实现。作用一般来讲是引入上一次解码的结果来加强隐形语言模型学习，在一些attention（例如transformer）中，也起到指示当前解码状态的作用。这个在attention机制的应用中比较普遍（可以追溯到最早的attention文章[1]的Sec 3.3.1中）。
> 
> [1] Bahdanau et al. Neural Machine Translation by Jointly Learning to Align and Translate. ICLR 2015.

非常感谢，新年快乐❤️
